- name: set up Frontend
  hosts: all
  become: true
  tasks: 
    - name: Install the latest version nginx
      ansible.builtin.yum:
        name: nginx
        state: latest
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: usr/share/nginx/html
        state: absent
    - name: Create Directory
      ansible.builtin.file:
        path: usr/share/nginx/html
        state: directory
    
    - name: download and extract content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy config file
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf

    - name: enable and start nginx service
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started 